x-generator: NSwag v14.1.0.0 (NJsonSchema v11.0.0.0 (Newtonsoft.Json v13.0.0.0))
openapi: 3.0.0
info:
  title: Carts.API
  version: v1
servers:
- url: https://localhost:7154
paths:
  /v1/carts:
    get:
      tags:
      - Carts
      - Carts
      operationId: Carts_GetCarts
      parameters:
      - name: page
        in: query
        schema:
          type: integer
          format: int32
          default: 1
        x-position: 1
      - name: pageSize
        in: query
        schema:
          type: integer
          format: int32
          default: 10
        x-position: 2
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PagedResultOfCart'
    post:
      tags:
      - Carts
      - Carts
      operationId: Carts_CreateCart
      requestBody:
        x-name: request
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateCartRequest'
        required: true
        x-position: 1
      responses:
        201:
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cart'
        404:
          description: ''
  /v1/carts/GetByTag/{tag}:
    get:
      tags:
      - Carts
      - Carts
      operationId: Carts_GetCartByTag
      parameters:
      - name: tag
        in: path
        required: true
        schema:
          type: string
        x-position: 1
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cart'
        404:
          description: ''
  /v1/carts/{id}:
    get:
      tags:
      - Carts
      - Carts
      operationId: Carts_GetCartById
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
        x-position: 1
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cart'
        404:
          description: ''
  /v1/carts/{id}/items:
    post:
      tags:
      - Carts
      - Carts
      operationId: Carts_AddCartItem
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
        x-position: 1
      requestBody:
        x-name: cartItemRequest
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AddCartItemRequest'
        required: true
        x-position: 2
      responses:
        201:
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CartItem'
        404:
          description: ''
  /v1/carts/{cartId}/items/{id}:
    get:
      tags:
      - Carts
      - Carts
      operationId: Carts_GetCartItemById
      parameters:
      - name: cartId
        in: path
        required: true
        schema:
          type: string
        x-position: 1
      - name: id
        in: path
        required: true
        schema:
          type: string
        x-position: 2
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CartItem'
        404:
          description: ''
    delete:
      tags:
      - Carts
      - Carts
      operationId: Carts_RemoveCartItem
      parameters:
      - name: cartId
        in: path
        required: true
        schema:
          type: string
        x-position: 1
      - name: id
        in: path
        required: true
        schema:
          type: string
        x-position: 2
      responses:
        200:
          description: ''
        404:
          description: ''
  /v1/carts/{cartId}/items/{id}/price:
    put:
      tags:
      - Carts
      - Carts
      operationId: Carts_UpdateCartItemPrice
      parameters:
      - name: cartId
        in: path
        required: true
        schema:
          type: string
        x-position: 1
      - name: id
        in: path
        required: true
        schema:
          type: string
        x-position: 2
      - name: price
        in: query
        required: true
        schema:
          type: number
          format: decimal
        x-position: 3
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CartItem'
        404:
          description: ''
  /v1/carts/{cartId}/items/{id}/quantity:
    put:
      tags:
      - Carts
      - Carts
      operationId: Carts_UpdateCartItemQuantity
      parameters:
      - name: cartId
        in: path
        required: true
        schema:
          type: string
        x-position: 1
      - name: id
        in: path
        required: true
        schema:
          type: string
        x-position: 2
      - name: quantity
        in: query
        required: true
        schema:
          type: integer
          format: int32
        x-position: 3
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CartItem'
        404:
          description: ''
  /v1/carts/{cartId}/items/{id}/data:
    put:
      tags:
      - Carts
      - Carts
      operationId: Carts_UpdateCartItemData
      parameters:
      - name: cartId
        in: path
        required: true
        schema:
          type: string
        x-position: 1
      - name: id
        in: path
        required: true
        schema:
          type: string
        x-position: 2
      - name: data
        in: query
        required: true
        schema:
          type: string
        x-position: 3
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CartItem'
        404:
          description: ''
  /v1/carts/{cartId}/items:
    delete:
      tags:
      - Carts
      - Carts
      operationId: Carts_ClearCart
      parameters:
      - name: cartId
        in: path
        required: true
        schema:
          type: string
        x-position: 1
      responses:
        200:
          description: ''
        404:
          description: ''
components:
  schemas:
    PagedResultOfCart:
      type: object
      additionalProperties: false
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/Cart'
        total:
          type: integer
          format: int32
    Cart:
      type: object
      additionalProperties: false
      properties:
        id:
          type: string
        tag:
          type: string
        total:
          type: number
          format: decimal
        items:
          type: array
          items:
            $ref: '#/components/schemas/CartItem'
        created:
          type: string
          format: date-time
        updated:
          type: string
          format: date-time
          nullable: true
    CartItem:
      type: object
      additionalProperties: false
      properties:
        id:
          type: string
        name:
          type: string
        image:
          type: string
          nullable: true
        productId:
          type: integer
          format: int64
          nullable: true
        productHandle:
          type: string
          nullable: true
        description:
          type: string
        price:
          type: number
          format: decimal
        vatRate:
          type: number
          format: double
          nullable: true
        regularPrice:
          type: number
          format: decimal
          nullable: true
        discountRate:
          type: number
          format: double
          nullable: true
        quantity:
          type: number
          format: double
        total:
          type: number
          format: decimal
        data:
          type: string
          nullable: true
        created:
          type: string
          format: date-time
        updated:
          type: string
          format: date-time
          nullable: true
    CreateCartRequest:
      type: object
      additionalProperties: false
      properties:
        tag:
          type: string
    AddCartItemRequest:
      type: object
      additionalProperties: false
      properties:
        name:
          type: string
        image:
          type: string
          nullable: true
        productId:
          type: integer
          format: int64
          nullable: true
        productHandle:
          type: string
          nullable: true
        description:
          type: string
        price:
          type: number
          format: decimal
        vatRate:
          type: number
          format: double
          nullable: true
        regularPrice:
          type: number
          format: decimal
          nullable: true
        discountRate:
          type: number
          format: double
          nullable: true
        quantity:
          type: integer
          format: int32
        data:
          type: string
          nullable: true
