x-generator: NSwag v14.1.0.0 (NJsonSchema v11.0.2.0 (Newtonsoft.Json v13.0.0.0))
openapi: 3.0.0
info:
  title: Analytics
  description: ''
  version: v1
servers:
- url: https://localhost:5091
paths:
  /v1/Client:
    post:
      tags:
      - Client
      summary: Initiate the client
      description: Registers a client for tracking.
      operationId: Client_InitClient
      requestBody:
        x-name: requestData
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ClientRegistrationRequestData'
        required: true
        x-position: 1
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: string
  /v1/Events:
    post:
      tags:
      - Events
      summary: Register an event
      description: Registers an event with data.
      operationId: Events_RegisterEvent
      parameters:
      - name: X-Client-Id
        x-originalName: clientId
        in: header
        schema:
          type: string
        x-position: 1
      - name: X-Session-Id
        x-originalName: sessionId
        in: header
        schema:
          type: string
        x-position: 2
      requestBody:
        x-name: dto
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EventData'
        required: true
        x-position: 3
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: string
        204:
          description: ''
  /v1/Session:
    post:
      tags:
      - Session
      summary: Initiate session
      description: Initiates a session for the current client. If the current session has expired a new one will be created and initiated.
      operationId: Session_InitSession
      parameters:
      - name: X-Client-Id
        x-originalName: clientId
        in: header
        schema:
          type: string
        x-position: 1
      requestBody:
        x-name: requestData
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SessionRequestData'
        required: true
        x-position: 2
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: string
  /v1/Session/Coordinates:
    post:
      tags:
      - Session
      summary: Register coordinates
      description: Registers the geo-coordinates to be attached to the session.
      operationId: Session_RegisterCoordinates
      parameters:
      - name: X-Client-Id
        x-originalName: clientId
        in: header
        schema:
          type: string
        x-position: 1
      - name: X-Session-Id
        x-originalName: sessionId
        in: header
        schema:
          type: string
        x-position: 2
      requestBody:
        x-name: coordinates
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Coordinates'
        required: true
        x-position: 3
      responses:
        200:
          description: ''
  /v1/Statistics/MostViewedItems:
    get:
      tags:
      - Statistics
      summary: Get most viewed items
      description: Returns the most viewed items over a specific period of time.
      operationId: Statistics_GetMostViewedItems
      parameters:
      - name: From
        in: query
        schema:
          type: string
          format: date-time
          nullable: true
        x-position: 1
      - name: To
        in: query
        schema:
          type: string
          format: date-time
          nullable: true
        x-position: 2
      - name: DistinctByClient
        in: query
        schema:
          type: boolean
          default: false
        x-position: 3
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Data'
  /v1/Statistics/GetSessionsCount:
    get:
      tags:
      - Statistics
      summary: Get sessions count
      description: Returns the number of sessions over a specific period of time.
      operationId: Statistics_GetSessionsCount
      parameters:
      - name: From
        in: query
        schema:
          type: string
          format: date-time
          nullable: true
        x-position: 1
      - name: To
        in: query
        schema:
          type: string
          format: date-time
          nullable: true
        x-position: 2
      - name: DistinctByClient
        in: query
        schema:
          type: boolean
          default: false
        x-position: 3
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Data'
  /v1/Statistics/GetSessionCoordinates:
    get:
      tags:
      - Statistics
      summary: Get session coordinates
      description: Returns the coordinates for sessions.
      operationId: Statistics_GetSessionCoordinates
      parameters:
      - name: From
        in: query
        schema:
          type: string
          format: date-time
          nullable: true
        x-position: 1
      - name: To
        in: query
        schema:
          type: string
          format: date-time
          nullable: true
        x-position: 2
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/SessionCoordinates'
components:
  schemas:
    ClientRegistrationRequestData:
      type: object
      description: The data being passed when registering a client.
      additionalProperties: false
      properties:
        userAgent:
          type: string
    EventData:
      type: object
      description: Container for data for an event, its type, and additional data, in the form of key-value pairs.
      additionalProperties: false
      properties:
        data:
          type: object
          additionalProperties: {}
        eventType:
          $ref: '#/components/schemas/EventType'
    EventType:
      type: string
      description: ''
      x-enumNames:
      - ProductViewed
      - ProductGroupViewed
      enum:
      - productViewed
      - productGroupViewed
    SessionRequestData:
      type: object
      description: The data being passed when requesting or renewing a session.
      additionalProperties: false
      properties:
        ipAddress:
          type: string
          nullable: true
    Coordinates:
      type: object
      description: Represents a set of geo-coordinates.
      additionalProperties: false
      properties:
        latitude:
          type: number
          format: double
        longitude:
          type: number
          format: double
    Data:
      type: object
      description: Represents the data of a graph, its series, and labels.
      additionalProperties: false
      properties:
        labels:
          type: array
          items:
            type: string
        series:
          type: array
          items:
            $ref: '#/components/schemas/Series'
    Series:
      type: object
      description: Represents a named series values.
      additionalProperties: false
      properties:
        name:
          type: string
        data:
          type: array
          items:
            type: number
            format: decimal
    SessionCoordinates:
      type: object
      description: Represents a session with its geo-coordinates.
      additionalProperties: false
      properties:
        dateTime:
          type: string
          format: date-time
        userAgent:
          type: string
        coordinates:
          $ref: '#/components/schemas/Coordinates'
  securitySchemes:
    JWT:
      type: apiKey
      description: 'Type into the textbox: Bearer {your JWT token}.'
      name: Authorization
      in: header
