x-generator: NSwag v14.1.0.0 (NJsonSchema v11.0.0.0 (Newtonsoft.Json v13.0.0.0))
openapi: 3.0.0
info:
  title: Analytics
  version: v1
servers:
- url: https://localhost:5091
paths:
  /v1/Client:
    post:
      tags:
      - Client
      operationId: Client_InitClient
      requestBody:
        x-name: data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ClientData'
        required: true
        x-position: 1
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: string
  /v1/Events:
    post:
      tags:
      - Events
      operationId: Events_RegisterEvent
      parameters:
      - name: X-Client-Id
        x-originalName: clientId
        in: header
        schema:
          type: string
        x-position: 1
      - name: X-Session-Id
        x-originalName: sessionId
        in: header
        schema:
          type: string
        x-position: 2
      requestBody:
        x-name: dto
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EventData'
        required: true
        x-position: 3
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: string
        204:
          description: ''
  /v1/Session:
    post:
      tags:
      - Session
      operationId: Session_InitSession
      parameters:
      - name: X-Client-Id
        x-originalName: clientId
        in: header
        schema:
          type: string
        x-position: 1
      requestBody:
        x-name: data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SessionData'
        required: true
        x-position: 2
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: string
  /v1/Session/Coordinates:
    post:
      tags:
      - Session
      operationId: Session_RegisterCoordinates
      parameters:
      - name: X-Client-Id
        x-originalName: clientId
        in: header
        schema:
          type: string
        x-position: 1
      - name: X-Session-Id
        x-originalName: sessionId
        in: header
        schema:
          type: string
        x-position: 2
      requestBody:
        x-name: coordinates
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Coordinates'
        required: true
        x-position: 3
      responses:
        200:
          description: ''
  /v1/Statistics/MostViewedItems:
    get:
      tags:
      - Statistics
      operationId: Statistics_GetMostViewedItems
      parameters:
      - name: From
        in: query
        schema:
          type: string
          format: date-time
          nullable: true
        x-position: 1
      - name: To
        in: query
        schema:
          type: string
          format: date-time
          nullable: true
        x-position: 2
      - name: DistinctByClient
        in: query
        schema:
          type: boolean
          default: false
        x-position: 3
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Data'
  /v1/Statistics/GetSessionsCount:
    get:
      tags:
      - Statistics
      operationId: Statistics_GetSessionsCount
      parameters:
      - name: From
        in: query
        schema:
          type: string
          format: date-time
          nullable: true
        x-position: 1
      - name: To
        in: query
        schema:
          type: string
          format: date-time
          nullable: true
        x-position: 2
      - name: DistinctByClient
        in: query
        schema:
          type: boolean
          default: false
        x-position: 3
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Data'
  /v1/Statistics/GetSessionCoordinates:
    get:
      tags:
      - Statistics
      operationId: Statistics_GetSessionCoordinates
      parameters:
      - name: From
        in: query
        schema:
          type: string
          format: date-time
          nullable: true
        x-position: 1
      - name: To
        in: query
        schema:
          type: string
          format: date-time
          nullable: true
        x-position: 2
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/SessionCoordinates'
components:
  schemas:
    ClientData:
      type: object
      additionalProperties: false
      properties:
        userAgent:
          type: string
    EventData:
      type: object
      additionalProperties: false
      properties:
        eventType:
          $ref: '#/components/schemas/EventType'
        data:
          type: object
          additionalProperties: {}
    EventType:
      type: string
      description: ''
      x-enumNames:
      - ProductViewed
      - ProductGroupViewed
      enum:
      - productViewed
      - productGroupViewed
    SessionData:
      type: object
      additionalProperties: false
      properties:
        ipAddress:
          type: string
          nullable: true
    Coordinates:
      type: object
      additionalProperties: false
      properties:
        latitude:
          type: number
          format: double
        longitude:
          type: number
          format: double
    Data:
      type: object
      additionalProperties: false
      properties:
        labels:
          type: array
          items:
            type: string
        series:
          type: array
          items:
            $ref: '#/components/schemas/Series'
    Series:
      type: object
      additionalProperties: false
      properties:
        name:
          type: string
        data:
          type: array
          items:
            type: number
            format: decimal
    SessionCoordinates:
      type: object
      additionalProperties: false
      properties:
        dateTime:
          type: string
          format: date-time
        userAgent:
          type: string
        coordinates:
          $ref: '#/components/schemas/Coordinates'
