x-generator: NSwag v14.1.0.0 (NJsonSchema v11.0.2.0 (Newtonsoft.Json v13.0.0.0))
openapi: 3.0.0
info:
  title: Store
  description: ''
  version: v1
servers:
- url: https://localhost:7188
paths:
  /Authentication/GetStatus:
    post:
      tags:
      - Authentication
      operationId: Authentication_GetStatus
      parameters:
      - name: referenceToken
        in: query
        schema:
          type: string
        x-position: 1
      responses:
        default:
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
        200:
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthenticationStatusResponse'
components:
  schemas:
    ProblemDetails:
      type: object
      additionalProperties:
        nullable: true
      properties:
        type:
          type: string
          nullable: true
        title:
          type: string
          nullable: true
        status:
          type: integer
          format: int32
          nullable: true
        detail:
          type: string
          nullable: true
        instance:
          type: string
          nullable: true
    AuthenticationStatusResponse:
      type: object
      additionalProperties: false
      properties:
        status:
          $ref: '#/components/schemas/BankIdStatus'
        qrCode:
          type: string
          nullable: true
    BankIdStatus:
      type: integer
      description: ''
      x-enumNames:
      - OutstandingTransaction
      - NoClient
      - Started
      - UserSign
      - UserReq
      - Complete
      - Error
      enum:
      - 0
      - 1
      - 2
      - 3
      - 4
      - 5
      - 6
  securitySchemes:
    JWT:
      type: apiKey
      description: 'Type into the textbox: Bearer {your JWT token}.'
      name: Authorization
      in: header
