x-generator: NSwag v14.1.0.0 (NJsonSchema v11.0.2.0 (Newtonsoft.Json v13.0.0.0))
openapi: 3.0.0
info:
  title: Notifications
  description: ''
  version: v1
servers:
- url: https://localhost:5030
paths:
  /Notifications:
    get:
      tags:
      - Notifications
      operationId: Notifications_GetNotifications
      parameters:
      - name: userId
        in: query
        schema:
          type: string
          nullable: true
        x-position: 1
      - name: tag
        in: query
        schema:
          type: string
          nullable: true
        x-position: 2
      - name: includeUnreadNotificationsCount
        in: query
        schema:
          type: boolean
          default: false
        x-position: 3
      - name: page
        in: query
        schema:
          type: integer
          format: int32
          default: 1
        x-position: 4
      - name: pageSize
        in: query
        schema:
          type: integer
          format: int32
          default: 5
        x-position: 5
      - name: sortBy
        in: query
        schema:
          type: string
          nullable: true
        x-position: 6
      - name: sortDirection
        in: query
        schema:
          oneOf:
          - nullable: true
            oneOf:
            - $ref: '#/components/schemas/SortDirection'
        x-position: 7
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotificationsResults'
    post:
      tags:
      - Notifications
      operationId: Notifications_CreateNotification
      requestBody:
        x-name: dto
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateNotification'
        required: true
        x-position: 1
      responses:
        200:
          description: ''
          content:
            application/octet-stream:
              schema:
                type: string
                format: binary
  /Notifications/{id}/MarkAsRead:
    post:
      tags:
      - Notifications
      operationId: Notifications_MarkNotificationAsRead
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
        x-position: 1
      responses:
        200:
          description: ''
          content:
            application/octet-stream:
              schema:
                type: string
                format: binary
  /Notifications/MarkAllAsRead:
    post:
      tags:
      - Notifications
      operationId: Notifications_MarkAllNotificationsAsRead
      responses:
        200:
          description: ''
          content:
            application/octet-stream:
              schema:
                type: string
                format: binary
  /Notifications/{id}:
    delete:
      tags:
      - Notifications
      operationId: Notifications_DeleteNotification
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
        x-position: 1
      responses:
        200:
          description: ''
          content:
            application/octet-stream:
              schema:
                type: string
                format: binary
  /Notifications/UnreadCount:
    get:
      tags:
      - Notifications
      operationId: Notifications_GetUnreadNotificationsCount
      parameters:
      - name: userId
        in: query
        schema:
          type: string
          nullable: true
        x-position: 1
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: integer
                format: int32
components:
  schemas:
    NotificationsResults:
      allOf:
      - $ref: '#/components/schemas/ResultsOfNotification'
      - type: object
        additionalProperties: false
        properties:
          unreadNotificationsCount:
            type: integer
            format: int32
            nullable: true
    ResultsOfNotification:
      type: object
      additionalProperties: false
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/Notification'
        totalCount:
          type: integer
          format: int32
    Notification:
      type: object
      additionalProperties: false
      properties:
        id:
          type: string
        content:
          type: string
          nullable: true
        tag:
          type: string
          nullable: true
        link:
          type: string
          nullable: true
        userId:
          type: string
          nullable: true
        isRead:
          type: boolean
        read:
          type: string
          format: date-time
          nullable: true
        published:
          type: string
          format: date-time
          nullable: true
        scheduledFor:
          type: string
          format: date-time
          nullable: true
        created:
          type: string
          format: date-time
        createdBy:
          type: string
        lastModified:
          type: string
          format: date-time
          nullable: true
        lastModifiedBy:
          type: string
          nullable: true
    SortDirection:
      type: string
      description: ''
      x-enumNames:
      - Desc
      - Asc
      enum:
      - Desc
      - Asc
    CreateNotification:
      type: object
      additionalProperties: false
      required:
      - content
      properties:
        content:
          type: string
          minLength: 1
        link:
          type: string
          nullable: true
        userId:
          type: string
          nullable: true
        scheduledFor:
          type: string
          format: date-time
          nullable: true
  securitySchemes:
    JWT:
      type: apiKey
      description: 'Type into the textbox: Bearer {your JWT token}.'
      name: Authorization
      in: header
