x-generator: NSwag v14.0.3.0 (NJsonSchema v11.0.0.0 (Newtonsoft.Json v13.0.0.0))
openapi: 3.0.0
info:
  title: Transactions
  version: v1
servers:
- url: https://localhost:5094
paths:
  /v1/transactions:
    post:
      tags:
      - Transactions
      - Transactions
      operationId: Transactions_PostTransactions
      requestBody:
        x-name: transactions
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/Transaction'
        required: true
        x-position: 1
      responses:
        200:
          description: ''
  /v1/transactions/{transactionId}/status:
    put:
      tags:
      - Transactions
      - Transactions
      operationId: Transactions_SetTransactionStatus
      parameters:
      - name: transactionId
        in: path
        required: true
        schema:
          type: string
        x-position: 1
      - name: status
        in: query
        required: true
        schema:
          $ref: '#/components/schemas/TransactionStatus'
        x-position: 2
      responses:
        200:
          description: ''
  /v1/transactions/{transactionId}/reference:
    put:
      tags:
      - Transactions
      - Transactions
      operationId: Transactions_SetTransactionReference
      parameters:
      - name: transactionId
        in: path
        required: true
        schema:
          type: string
        x-position: 1
      - name: reference
        in: query
        required: true
        schema:
          type: string
        x-position: 2
      responses:
        200:
          description: ''
  /v1/Transactions:
    get:
      tags:
      - Transactions
      operationId: Transactions_GetTransactions
      parameters:
      - name: page
        in: query
        schema:
          type: integer
          format: int32
        x-position: 1
      - name: pageSize
        in: query
        schema:
          type: integer
          format: int32
        x-position: 2
      - name: status
        in: query
        style: form
        explode: true
        schema:
          type: array
          nullable: true
          items:
            $ref: '#/components/schemas/TransactionStatus'
        x-position: 3
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ItemsResultOfTransaction'
components:
  schemas:
    Transaction:
      type: object
      additionalProperties: false
      properties:
        id:
          type: string
        date:
          type: string
          format: date-time
          nullable: true
        status:
          $ref: '#/components/schemas/TransactionStatus'
        from:
          type: string
        reference:
          type: string
        currency:
          type: string
        amount:
          type: number
          format: decimal
    TransactionStatus:
      type: string
      description: ''
      x-enumNames:
      - Unverified
      - Verified
      - Payback
      - Unknown
      enum:
      - Unverified
      - Verified
      - Payback
      - Unknown
    ItemsResultOfTransaction:
      type: object
      additionalProperties: false
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/Transaction'
        totalItems:
          type: integer
          format: int32
  securitySchemes:
    JWT:
      type: apiKey
      description: 'Type into the textbox: Bearer {your JWT token}.'
      name: Authorization
      in: header
